# Generated by Django 4.1.3 on 2022-11-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
